# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e3f2f1a2ed85d6f50ae6e3d0e1359428281fa4ebc2465bd6e928ce2244266b5434181c21105452622eb34b978d5bda1020a3a6237909e0dfaaffb0e71cba7c3

test:
  secret_key_base: 1be2407a11f6660b48615584df281d4dd7592d7bc2d7561a44336e4ba6a1db27d668a6c10c034809c118e84344d821c6691ce38f72aac5c0d8ffc9cbf37c474c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
